### PR TITLE
Add Proxy

### PR DESCRIPTION
**Pull request by jakjus**
As discussed in https://github.com/mertushka/haxball.js/issues/9

### CODE REVIEW

**Review by mertushka — CHANGES_REQUESTED** [review]
`https-proxy-agent` must be added in package.json

**Comment by jakjus** [comment]
Wow great changes, thanks~
From what I understand, adding it to `m()` is like a variable lookup in RoomConfig? Then I'll also add it to type definitions for room config as an optional field.

**Comment by mertushka** [comment]
> Wow great changes, thanks~

You're welcome. Thats all i can do on basro's 'minified' source code..

> Adding it to `m()` is like a variable lookup in RoomConfig?

Exactly.

You should add `debug: boolean` option in `RoomConfigObject` definition too. It toggles WebSocket error messages. Then we can publish `2.1.2`.

**Review by mertushka — APPROVED** [review]

**Comment by jakjus** [comment]
Done! Ready to merge.

**Pull request merged**
